# Generated by Django 4.0.4 on 2022-04-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('query', models.TextField(max_length=500)),
                ('phone', models.IntegerField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
